### ISSUE TITLE
Handshake ssl failed

### ISSUE THREAD

**Issue by Gadgetroch** [Pointifix/AutoTranslate#2]
Hi,

when i put my token, i have an issue about handshake ssl failed.

Can you help ?

Do you have a discord or something ? I want ask for something else.

Thank's

**Comment by Pointifix** [comment]
Hello, I had the same issue, I had to replace the modules folder from the Java version coming with mindustry with the modules folder of my local Java installation. Check out the [releases page](https://github.com/Pointifix/AutoTranslate/releases) there is a short description of what to do in order for it to work.
